### PR TITLE
fip-002

### PR DESCRIPTION
**Pull request by rgvnFET**
`fip`: 002
`title`: Raise max_gas setting and max bytes per block
`author`: Fetch Foundation (developer@fetch.ai)
`description`: Raise max_gas setting to 3M from 2M and increase the max bytes per block from 200KB to 300KB.
`discussions-to`: 
`status`: Accepted
`type`: Ecosystem
`created`: 2022-07-19
`requires`:
`Withdrawal-reason`:
`review-deadline`: 2022-07-22
`last-call`: 2022-07-21
`author-response-wait-time`: 1 hour

### CODE REVIEW

**Review by Atari-buzzk1LL — APPROVED** [review]
I think that this FIP is a necessity for all current and future projects to be able to utilize more complex smart contracts, and seeing that the max_gas setting of 3M gas has been effective on the Dorado testnet it should now be applied to the mainnet.

**Comment by psy2848048** [comment]
Some heavy contracts goes over 300KB. `max_byte` seems to be raised as 400KB

**Comment by rgvnFET** [comment]
> 
No significant trade offs. The gas fees are pretty much negligible and with the suggested increase, it would still remain negligible. 

Future Dapp deployments should not be limited by the current parameters and given we have tested it on Dorado with suggested parameters and as those trials were successful, it only makes sense for us to finally implement the same on the mainnet.

**Comment by VijaySharma815** [comment]
Gov proposal now live on chain: https://www.mintscan.io/fetchai/proposals/8

**Review by VijaySharma815 — APPROVED** [review]

**Pull request merged**
